############ Used for most of the experiments ############

submission_ready: True

# save_predictions_to_disk: True # True or False
load_from_checkpoint: logs/20241015_105623_ManualTune-Baseline-DemographicsEssayAugmented-TrainedWith2023And2022/lightning_logs/version_16745665/checkpoints/epoch=13-step=4620.ckpt

####### 2023 ########
# test_file_list: ["data/NewsEmp2023/WASSA23_essay_level_test.tsv"]

test_file_list: ["data/ProcessedNewsEmp/WASSA23_essay_level_test_demographic-essay.tsv"]
