############ Used for most of the experiments ############

# Boolean flags. No need to provide values 
# --submission_ready:

save_predictions_to_disk: False # True or False
load_from_checkpoint: logs/20241026_205612_SieBERT/lightning_logs/version_17661371/checkpoints/epoch=8-step=567.ckpt
# test_file_list: ["data/NewsEmp2023/WASSA23_essay_level_test.tsv"]
test_file_list: ["data/NewsEmp2024/test_data_with_labels/goldstandard_EMP.csv"]
