# common between train and test
num_workers: 12
plm: roberta-base
# plm: siebert/sentiment-roberta-large-english

max_length: 512
fc_arch: [768, 512, 256, 1] # [out_transforer, out_pre_fusion, out_fusion, out]
label_column: empathy
llm_column: llm_empathy
feature_to_tokenise: ["essay"]
# feature_to_tokenise: ["demographic_essay"]
# extra_columns_to_keep: ["article_id"]
extra_columns_to_keep: []

use_demographics: False
