############ Used for most of the experiments ############

# Boolean flags. No need to provide values 
# --submission_ready:

save_predictions_to_disk: True # True or False
load_from_checkpoint: logs/20241018_142941_ReproduceWASSA2024Paper/lightning_logs/version_16840263/checkpoints/epoch=2-step=687.ckpt

# test_file_list: ["data/NewsEmp2023/WASSA23_essay_level_test.tsv"]
test_file_list: ["data/NewsEmp2024/test_data_with_labels/goldstandard_EMP.csv"]
