############ NOT used if any load_from_checkpoint is provided #######

# expt_name: Baseline
# expt_name: DetectNoiseLabels_Agentic_v2_v3
# expt_name: DetectNoiseLabels_Agentic_Onlyv3
expt_name: DetectNoiseLabels_Agentic_Onlyv3

############ Used for most of the experiments ############

seed: 0
num_workers: 12
plm: roberta-base
num_epochs: 10
lr: 1.0e-5
batch_size: 16
logging_dir: ./logs

load_from_checkpoint: False # False or path to checkpoint file (.ckpt) of the vanilla model (not the agentic models)

save_predictions_to_disk: False # won't save during val

label_column: empathy
llm_column: llm_empathy
feature_to_tokenise: ["essay"]
# extra_columns_to_keep: ["article_id"]
extra_columns_to_keep: []

### extra column in train only
extra_columns_to_keep_train: ["llm_empathy"]

max_length: 512
demographics: []
# demographics: ['gender', 'education', 'race', 'age', 'income']

val_file_list: ["data/NewsEmp2023/WASSA23_essay_level_dev.tsv"]

############ 2022 and 2023 ############
# train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS_with_LLM.tsv", "./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]

### for 2022 and 2023, we have separate gold standard files
val_goldstandard_file: data/NewsEmp2023/goldstandard_dev.tsv

############ 2022 only ############


############ 2023 only ############
train_file_list: ["./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]


############ Agentic approach ############
noise_level: 0.5
num_agents: 5
save_agentics_to_disk: False # True or False

# updated_train_dl_file: False
updated_train_dl_file: logs/20240926_113249_DetectNoiseLabels_Agentic_v2_v3/updated_train_dl.pt
