# expt_name: Baseline-RoBERTa-GoodSamples
# expt_name: RoBERTa-SSL-Old2New
expt_name: DetectNoiseLabels_Agentic
seed: 42
num_workers: 12
cuda_visible_devices: 2,

checkpoint: roberta-base
# checkpoint: mistralai/Mistral-7B-v0.1

k_fold: 10
use_lora: False

data:
  train_file: ./data/v2_v3_train.tsv
  # train_file: ./data/v2_v3_train_augmented_labelled_0.5.tsv
  val_file: ./data/v2_dev.tsv
  feature_to_tokenise: ['demographic_essay']
  max_length: 512
  demographics: []
  # demographics: ['gender', 'education', 'race', 'age', 'income']
  ssl_threshold: 0.5
  noise_level: 20

train:
  num_epochs: 20
  num_agents: 5
  logging_dir: ./logs
  # checkpoint_dir: False
  checkpoint_dir: ./logs/20240904_193336_DetectNoiseLabels_Agentic/
  lr: 1.0e-4
  lr_scheduler_type: constant
  lr_step_period: 10
  warmup_ratio: 0.1
  max_grad_norm: 0.3
  batch_size: 32
  weight_decay: 0.001
  fp16: False
  gradient_checkpointing: True
  dropout: 0.2
