debug_mode: False

expt_name: Agentic-2022-2023-EssayDn

############ Agentic approach ############
noise_level: 0.3
num_agents: 3
save_agentics_to_disk: True # saves indices and updated train_dl file

save_predictions_to_disk: False # so that we don't save all val steps each epoch

############ 2022 and 2023 ############
train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS_with_LLM.tsv", "./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]

### for 2022 and 2023, we have separate gold standard files

############ 2022 ############
# train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS_with_LLM.tsv"]
# val_file_list: ["data/NewsEmp2022/messages_dev_features_ready_for_WS_2022.tsv"]
# val_goldstandard_file: data/NewsEmp2022/goldstandard_dev_2022.tsv

############ 2023 ############
# train_file_list: ["./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]
val_file_list: ["data/NewsEmp2023/WASSA23_essay_level_dev.tsv"]
val_goldstandard_file: data/NewsEmp2023/goldstandard_dev.tsv
