debug_mode: False # will run only 1 epoch of training with 1% of training data, saves logs in tmp/ directory

do_test: True # whether to run subsequent test or not; required on trained on tuned hyperparameters
save_predictions_to_disk: False # True or False

main_label: y # y' - LLM-GEm; y - vanilla

train_data: [2024] # for y or y'
train_only_llm_data: [] # for y_llm

expt_name_postfix: MultiHparam-Demog-10Epoch # postfix to be added on top of main_label, train_data and train_only_llm_data
# overwrite_logging_dir: logs/20241109_154046_y'(2024,2023,2022)-MultiHparam-Demog-10Epoch 
overwrite_logging_dir: tmp
# resume_train_from_checkpoint: logs/20241023_205914_vanilla+2023LLM/lightning_logs/version_17110004/checkpoints/epoch=5-step=378.ckpt

finetune_from_checkpoint: logs/20241101_014137_y'(2024,2023,2022)-MultiHparam/lr_3e-05_bs_16/alpha_4.5/seed_42/lightning_logs/version_17961088/checkpoints/epoch=9-step=2590.ckpt 
finetune_lr: 3.0e-6

num_epochs: 10
# seeds: [0, 42, 100, 999, 1234]
seeds: [42]

tune_hparams: False

# lrs: [1.0e-5, 2.0e-5, 3.0e-5]
# batch_sizes: [16, 32]

tuned_lr: 3.0e-05
tuned_batch_size: 16
tuned_alpha: 4.5

logging_dir: ./logs
freeze_plm: False
lr_find: False  # it didn't work for me

adamw_beta1: 0.9
adamw_beta2: 0.98
adamw_eps: 1.0e-06
adamw_weight_decay: 0.1

use_lr_scheduler: False
lr_scheduler_type: linear
# lr_scheduler_type: polynomial

warmup_ratio: 0.06

# lr_scheduler_type: plateau
# plateau_patience: 1
# plateau_factor: 0.05
# plateau_threshold: 1.0e-4

# all file list that we can use for training / validation / testing
2024:
    train: data/NewsEmp2024/trac3_EMP_train.csv
    train_llama: data/NewsEmp2024/trac3_EMP_train_llama.tsv
    val: data/NewsEmp2024/trac3_EMP_dev.csv
    val_llama: data/NewsEmp2024/trac3_EMP_dev_llama.csv
    test: data/NewsEmp2024/test_data_with_labels/goldstandard_EMP.csv
2023:
    train: data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv
    train_llama: data/NewsEmp2023/WASSA23_essay_level_with_labels_train_llama.tsv
    val: data/NewsEmp2023/WASSA23_essay_level_dev.tsv 
    val_llama: data/NewsEmp2023/WASSA23_essay_level_dev_llama.tsv
2022:
    train: data/NewsEmp2022/messages_train_ready_for_WS.tsv
    train_llama: data/NewsEmp2022/messages_train_ready_for_WS_llama.tsv
    val: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022.tsv
    val_llama: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022_llama.tsv
    