############ NOT used if any load_from_checkpoint or updated_train_dl_file is provided #######


# boolean flags. No need to provide values
--debug_mode:

expt_name: ReproduceWASSA2024Paper30Epochs

val_only: False

# load_from_checkpoint: logs/20241017_222547_TrainedWith-2023-EssayDn-LLMGEm/lightning_logs/version_16840263/checkpoints/epoch=10-step=539.ckpt

save_predictions_to_disk: False # so that we don't save all val steps each epoch

# updated_train_dl_file: ./logs/20241017_124809_Agentic-2022-2023-EssayDn/updated_train_dl.pt

train_file_list: ["data/NewsEmp2024/trac3_EMP_train.csv", "data/NewsEmp2022/messages_train_ready_for_WS.tsv", "./data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv"]

############ 2022 and 2023 ############
# train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS_with_LLM.tsv", "./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]
### for 2022 and 2023, we have separate gold standard files

############ 2022 ############
# train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS_with_LLM.tsv"]
# val_file_list: ["data/NewsEmp2022/messages_dev_features_ready_for_WS_2022.tsv"]
# val_goldstandard_file: data/NewsEmp2022/goldstandard_dev_2022.tsv

############ 2023 ############
# train_file_list: ["./data/NewsEmp2023/WASSA23_essay_level_with_labels_train_with_LLM.tsv"]
# val_file_list: ["data/NewsEmp2023/WASSA23_essay_level_dev.tsv"]
# val_goldstandard_file: data/NewsEmp2023/goldstandard_dev.tsv

############ 2024 ############
# train_file_list: ["data/NewsEmp2024/trac3_EMP_train.csv"]
val_file_list: ["data/NewsEmp2024/trac3_EMP_dev.csv"]
