# expt_name: Baseline_v3
# expt_name: RoBERTa-SSL-Old2New
expt_name: DetectNoiseLabels_Agentic_v3
# expt_name: Debug
seed: 42
num_workers: 12

checkpoint: roberta-base

k_fold: 10
use_lora: False

data:
  train_file: ./data/v2_v3_train.tsv
  # train_file: ./data/v2_v3_train_augmented_labelled_0.5.tsv
  # val_file: ./data/v2_dev.tsv
  val_file: ./data/v3_dev.tsv
  feature_to_tokenise: ['demographic_essay']
  max_length: 512
  demographics: []
  # demographics: ['gender', 'education', 'race', 'age', 'income']
  ssl_threshold: 0.5
  noise_level: 20
  mc_index_file: ./logs/20240905_113618_DetectNoiseLabels_Agentic/mc_index_20.npy
  lc_index_file: ./logs/20240905_113618_DetectNoiseLabels_Agentic/lc_index_20.npy

train:
  num_epochs: 10
  num_agents: 5
  logging_dir: ./logs
  checkpoint_dir: False
  # checkpoint_dir: ./logs/20240905_134322_DetectNoiseLabels_Agentic/
  lr: 1.0e-4
  lr_scheduler_type: constant
  lr_step_period: 10
  warmup_ratio: 0.1
  max_grad_norm: 0.3
  batch_size: 32
  weight_decay: 0.001
  fp16: False
  gradient_checkpointing: False # segfault, probably due to this; https://discuss.huggingface.co/t/segmentation-fault-with-gradient-checkpointing-on-multigpu/51496
  dropout: 0.2
