############ NOT used if any (resume)checkpoint is provided #######

expt_name: Baseline
# expt_name: DetectNoiseLabels_Agentic_Onlyv3
# expt_name: DetectNoiseLabels_Agentic_Onlyv3
# expt_name: Debug

############ Used for most of the experiments ############

seed: 0
num_workers: 12
plm: roberta-base
num_epochs: 10
lr: 1.0e-5
batch_size: 16
logging_dir: ./logs
resume_from_checkpoint: False


train_file_list: ["data/NewsEmp2022/messages_train_ready_for_WS.tsv", "./data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv"]
# train_file_list: ["./data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv"]
# train_file_list: ./data/v2_v3_train_augmented_labelled_0.5.tsv
label_column: empathy

val_file_list: ["data/NewsEmp2023/WASSA23_essay_level_dev.tsv"]
### for 2022 and 2023, we have separate gold standard files
val_goldstandard_file: data/NewsEmp2023/goldstandard_dev.tsv

############ v2 only ############



############ v3 only ############
# train_file_list: ["./data/WASSA2023/WASSA23_essay_level_with_labels_train.tsv"]


# feature_to_tokenise: ['demographic_essay']

feature_to_tokenise: ["essay"]
extra_columns_to_keep: ["article_id"]
max_length: 512
demographics: []
# demographics: ['gender', 'education', 'race', 'age', 'income']

############ For Agentic approach ############
noise_level: 10
num_agents: 5
mc_index_file: False
lc_index_file: False

# mc_index_file: ./logs/20240904_193336_DetectNoiseLabels_Agentic/mc_index_50.npy
# lc_index_file: ./logs/20240904_193336_DetectNoiseLabels_Agentic/lc_index_50.npy

