# boolean flags. No need to provide values
# --debug_mode: # will run only 1 epoch of training with 1% of training data, saves logs in tmp/ directory

do_test: False # whether to run subsequent test or not
# do_test: True
save_predictions_to_disk: False # True or False

# main_label: y
main_label: y' # means a sweep over alpha range

train_data: [2024, 2023, 2022]
train_only_llm_data: [] # basically, y_llm

expt_name_postfix: MultiHparam # postfix to be added on top of main_label, train_data and train_only_llm_data

# resume_train_from_checkpoint: logs/20241023_205914_vanilla+2023LLM/lightning_logs/version_17110004/checkpoints/epoch=5-step=378.ckpt
# val_from_checkpoint:
# finetune_from_checkpoint: logs/20241023_213441_LLMGEm+2023LLM/lightning_logs/version_17195570/checkpoints/epoch=19-step=1260.ckpt

# updated_train_dl_file: ./logs/20241017_124809_Agentic-2022-2023-EssayDn/updated_train_dl.pt

# all file list that we can use for training / validation / testing
2024:
    train: data/NewsEmp2024/trac3_EMP_train.csv
    train_llama: data/NewsEmp2024/trac3_EMP_train_llama.tsv
    val: data/NewsEmp2024/trac3_EMP_dev.csv
    val_llama: data/NewsEmp2024/trac3_EMP_dev_llama.csv
    test: data/NewsEmp2024/test_data_with_labels/goldstandard_EMP.csv
2023:
    train: data/NewsEmp2023/WASSA23_essay_level_with_labels_train.tsv
    train_llama: data/NewsEmp2023/WASSA23_essay_level_with_labels_train_llama.tsv
    val: data/NewsEmp2023/WASSA23_essay_level_dev.tsv 
    val_llama: data/NewsEmp2023/WASSA23_essay_level_dev_llama.tsv
2022:
    train: data/NewsEmp2022/messages_train_ready_for_WS.tsv
    train_llama: data/NewsEmp2022/messages_train_ready_for_WS_llama.tsv
    val: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022.tsv
    val_llama: data/NewsEmp2022/messages_dev_features_ready_for_WS_2022_llama.tsv